# This uses newer and faster docker based build system
sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

php:
  # PHP 7.0
  # - nightly 
  - 5.6
#  - 5.5
#  - 5.4
#  - 5.3
#  - 5.2

env:
  - WP_PROJECT_TYPE=theme WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000  WP_TEST_USER=test WP_TEST_USER_PASS=test
  - WP_PROJECT_TYPE=theme WP_VERSION=latest WP_MULTISITE=1 WP_TEST_URL=http://localhost:12000  WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  allow_failures:
  #  - php: nightly
  - php: 5.6

before_script:
  # Install composer packages before trying to activate themes or plugins
  # - composer install

  - git clone https://github.com/Koodimonni/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
  - cd wp-tests/spec && bundle exec rspec test.rb
  - phpcs --standard=./codesniffer.ruleset.xml ./**/*.php 